DROP TABLE IF EXISTS STAGE CASCADE;
DROP TABLE IF EXISTS COURS CASCADE;
DROP TABLE IF EXISTS SESSION CASCADE;
DROP TABLE IF EXISTS CONSTITUER CASCADE;
DROP TABLE IF EXISTS ENTREPRISE CASCADE;
DROP TABLE IF EXISTS FORMATEUR CASCADE;
DROP TABLE IF EXISTS STAGIAIRE CASCADE;
DROP TABLE IF EXISTS INSCRIPTION CASCADE;
DROP TABLE IF EXISTS PRESENCE CASCADE;

--PK
CREATE TABLE STAGE(
    NomStage CHAR(50) PRIMARY KEY,
    Duree INTEGER
);

CREATE TABLE COURS(
    NumCours INTEGER PRIMARY KEY,
    TrancheHoraire CHAR(50),
    Contenu CHAR(50)
);

CREATE TABLE ENTREPRISE(
    RefEntr INTEGER PRIMARY KEY,
    NomEntr CHAR(50),
    RespForm CHAR(50)
);

CREATE TABLE FORMATEUR(
    NumForm INTEGER PRIMARY KEY,
    NomForm CHAR(50),
    AdrForm CHAR(50)
);

--PK et FK
CREATE TABLE SESSION(
    NumSession INTEGER PRIMARY KEY,
    DateDebut DATE,
    NomStage CHAR(50),
    CONSTRAINT fk_NomStage FOREIGN KEY(NomStage) REFERENCES STAGE(NomStage)
);

CREATE TABLE STAGIAIRE(
    NumStagiaire INTEGER PRIMARY KEY,
    NomStagiaire CHAR(50),
    AdrStagiaire CHAR(50),
    RefEntr INTEGER,
    CONSTRAINT fk_RefEntr FOREIGN KEY(RefEntr) REFERENCES ENTREPRISE(RefEntr)
);

--PK(FK, FK)
CREATE TABLE CONSTITUER(
    NomStage CHAR(50),
    NumCours INTEGER,
    CONSTRAINT pk_stage PRIMARY KEY(NomStage, NumCours),
    CONSTRAINT fk_NomStage FOREIGN KEY(NomStage) REFERENCES STAGE(NomStage),
    CONSTRAINT fk_NumCours FOREIGN KEY(NumCours) REFERENCES COURS(NumCours)
);

CREATE TABLE INSCRIPTION(
    NumSession INTEGER,
    NumStagiaire INTEGER,
    DateInscription Date,
    CONSTRAINT pk_inscription PRIMARY KEY(NumSession, NumStagiaire),
    CONSTRAINT fk_NumSession FOREIGN KEY(NumSession) REFERENCES SESSION(NumSession),
    CONSTRAINT fk_NumStagiaire FOREIGN KEY(NumStagiaire) REFERENCES STAGIAIRE(NumStagiaire)
);

CREATE TABLE PRESENCE(
    NumSession INTEGER,
    NumStagiaire INTEGER,
    CONSTRAINT pk_presence PRIMARY KEY(NumSession, NumStagiaire),
    CONSTRAINT fkpresence_NumSession FOREIGN KEY(NumSession) REFERENCES SESSION(NumSession),
    CONSTRAINT fkpresence_NumStagiaire FOREIGN KEY(NumStagiaire) REFERENCES STAGIAIRE(NumStagiaire)
);

CREATE TABLE INTERVENTION(
    NumForm INTEGER,
    NumSession INTEGER,
    NumCours INTEGER,
    Date DATE,
    CONSTRAINT pk_intervention PRIMARY KEY(NumForm, NumSession, NumCours),
    CONSTRAINT fkintervention_NumForm FOREIGN KEY(NumForm) REFERENCES FORMATEUR(NumForm),
    CONSTRAINT fkintervention_NumSession FOREIGN KEY(NumSession) REFERENCES SESSION(NumSession),
    CONSTRAINT fkintervention_NumCours FOREIGN KEY(NumCours) REFERENCES COURS(NumCours)
);
--End