--Formule1 DROPPING
DROP TABLE IF EXISTS CIRCUIT CASCADE;
DROP TABLE IF EXISTS PNEUS CASCADE;
DROP TABLE IF EXISTS VOITURE CASCADE;

DROP TABLE IF EXISTS GRANDPRIX CASCADE;
DROP TABLE IF EXISTS QUALIFIER CASCADE;
DROP TABLE IF EXISTS COURIR CASCADE;
DROP TABLE IF EXISTS PILOTE CASCADE;
DROP TABLE IF EXISTS SUBVENTIONNER CASCADE;
DROP TABLE IF EXISTS ECURIE CASCADE;
DROP TABLE IF EXISTS SOUTENIR CASCADE;
DROP TABLE IF EXISTS SPONSPOR CASCADE;

--PK only
CREATE TABLE CIRCUIT(
    NomCircuit CHAR(50) PRIMARY KEY,
    Pays CHAR(50),
    LgPiste NUMERIC,
    NbSpectateur INTEGER
);

CREATE TABLE PNEUS(
    NomFournisseur CHAR(50) PRIMARY KEY,
    DateAccreditation DATE
);

CREATE TABLE VOITURE(
    NumVoiture INTEGER PRIMARY KEY,
    TypeVoiture CHAR(50)
);

--PK et FKs
CREATE TABLE ECURIE(
    NomEcurie CHAR(50) PRIMARY KEY,
    AdrSiegeEcurie CHAR(250),
    NomDirecteurSportif CHAR(50),
    NomFournisseur CHAR(50),
    CONSTRAINT fk_NomFournisseur FOREIGN KEY(NomFournisseur) REFERENCES PNEUS(NomFournisseur)
);

CREATE TABLE PILOTE(
    NumPilote INTEGER PRIMARY KEY,
    NomPilote CHAR(50),
    PrenomPilote CHAR(50),
    AgePilote INTEGER,
    NomEcurie CHAR(50),
    NumVoiture INTEGER,
    CONSTRAINT fk_NomEcurie FOREIGN KEY(NomEcurie) REFERENCES ECURIE(NomEcurie),
    CONSTRAINT fk_NumVoiture FOREIGN KEY(NumVoiture) REFERENCES VOITURE(NumVoiture)
);

CREATE TABLE GRANDPRIX(
    NomGP CHAR(50) PRIMARY KEY,
    NbTours INTEGER,
    NbVoitures INTEGER,
    NomCircuit CHAR(50),
    CONSTRAINT fk_NomCircuit FOREIGN KEY(NomCircuit) REFERENCES CIRCUIT(NomCircuit)
);

CREATE TABLE SPONSPOR(
    NomEntreprise CHAR(50) PRIMARY KEY,
    AdrSiege CHAR(200),
    NumPilote INTEGER,
    CONSTRAINT fk_NumPilote FOREIGN KEY(NumPilote) REFERENCES PILOTE(NumPilote)
);

--PK(FK, FK)
CREATE TABLE QUALIFIER(
    NomGP CHAR(50),
    NomCircuit CHAR(50),
    Classement INTEGER,
    CONSTRAINT pk_qualifier PRIMARY KEY(NomGP, NomCircuit),
    CONSTRAINT fk_NomGP FOREIGN KEY(NomGP) REFERENCES GRANDPRIX(NomGP),
    CONSTRAINT fk_NomCircuit FOREIGN KEY(NomCircuit) REFERENCES CIRCUIT(NomCircuit)
);

CREATE TABLE COURIR(
    NomGP CHAR(50),
    NomCircuit CHAR(50),
    NbPoints INTEGER,
    CONSTRAINT pk_courir PRIMARY KEY(NomGP, NomCircuit),
    CONSTRAINT fk_NomGP FOREIGN KEY(NomGP) REFERENCES GRANDPRIX(NomGP),
    CONSTRAINT fk_NomCircuit FOREIGN KEY(NomCircuit) REFERENCES CIRCUIT(NomCircuit)
);

CREATE TABLE SUBVENTIONNER(
    NomEntreprise CHAR(50),
    NumPilote INTEGER,
    CONSTRAINT pk_subventionner PRIMARY KEY(NomEntreprise, NumPilote),
    CONSTRAINT fk_NomEntreprise FOREIGN KEY(NomEntreprise) REFERENCES SPONSPOR(NomEntreprise),
    CONSTRAINT fk_NumPilote FOREIGN KEY(NumPilote) REFERENCES PILOTE(NumPilote)
);

CREATE TABLE SOUTENIR(
    NomEntreprise CHAR(50),
    NomEcurie CHAR(50),
    CONSTRAINT pk_soutenir PRIMARY KEY(NomEntreprise, NomEcurie),
    CONSTRAINT fk_NomEntreprise FOREIGN KEY(NomEntreprise) REFERENCES SPONSPOR(NomEntreprise),
    CONSTRAINT fk_NomEcurie FOREIGN KEY(NomEcurie) REFERENCES ECURIE(NomEcurie)
);
--End